In [174]:
import pandas as pd 
import numpy as np

In [175]:
# Load the dataset
df = pd.read_csv("data/WB_WDI_EG_ELC_ACCS_ZS.csv")

In [176]:
# View the dataset
df.head(10)

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,REF_AREA,INDICATOR,SEX,AGE,URBANISATION,UNIT_MEASURE,...,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3_LABEL,AGG_METHOD_LABEL,UNIT_TYPE_LABEL,DECIMALS_LABEL,DATABASE_ID_LABEL,TIME_FORMAT_LABEL,UNIT_MULT_LABEL,OBS_STATUS_LABEL,OBS_CONF_LABEL
0,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,UZB,WB_WDI_EG_ELC_ACCS_ZS,_T,_T,_T,PT_POP,...,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
1,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,VUT,WB_WDI_EG_ELC_ACCS_ZS,_T,_T,_T,PT_POP,...,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
2,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,VEN,WB_WDI_EG_ELC_ACCS_ZS,_T,_T,_T,PT_POP,...,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
3,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,VNM,WB_WDI_EG_ELC_ACCS_ZS,_T,_T,_T,PT_POP,...,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
4,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,VIR,WB_WDI_EG_ELC_ACCS_ZS,_T,_T,_T,PT_POP,...,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
5,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,PSE,WB_WDI_EG_ELC_ACCS_ZS,_T,_T,_T,PT_POP,...,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
6,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,YEM,WB_WDI_EG_ELC_ACCS_ZS,_T,_T,_T,PT_POP,...,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
7,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,ZMB,WB_WDI_EG_ELC_ACCS_ZS,_T,_T,_T,PT_POP,...,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
8,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,ZWE,WB_WDI_EG_ELC_ACCS_ZS,_T,_T,_T,PT_POP,...,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,World Development Indicators (WDI),Annual,Units,Normal value,Public
9,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,AFE,WB_WDI_EG_ELC_ACCS_ZS,_T,_T,_T,PT_POP,...,Not Applicable,Not Applicable,Not Applicable,Ratio,Two,World Development Indicators (WDI),Annual,Units,Normal value,Public

In [177]:
df= df[['REF_AREA','REF_AREA_LABEL','TIME_PERIOD','OBS_VALUE']]
df.columns=['countryCode','countryName','year','electricityAccess']

In [178]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7859 entries, 0 to 7858
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   countryCode        7859 non-null   str
 1   countryName        7859 non-null   str
 2   year               7859 non-null   int64
 3   electricityAccess  7859 non-null   float64
dtypes: float64(1), int64(1), str(2)
memory usage: 245.7 KB

In [179]:
df.head(20)

   countryCode                     countryName  year  electricityAccess
0          UZB                      Uzbekistan  1999          99.514114
1          VUT                         Vanuatu  1999          19.100000
2          VEN                   Venezuela, RB  1999          98.900000
3          VNM                         Vietnam  1999          86.994438
4          VIR           Virgin Islands (U.S.)  1999         100.000000
5          PSE              West Bank and Gaza  1999          98.623154
6          YEM                     Yemen, Rep.  1999          47.992947
7          ZMB                          Zambia  1999          18.540245
8          ZWE                        Zimbabwe  1999          38.400000
9          AFE       Eastern & Southern Africa  2000          19.917256
10         AFW        Western & Central Africa  2000          34.246116
11         ARB                      Arab World  2000          80.458667
12         CSS          Caribbean small states  2000          88.415929
13         CEB  Central Europe and the Baltics  2000          97.926264
14         EAR      Early-demographic dividend  2000          67.500489
15         EAS             East Asia & Pacific  2000          92.061814
16         ZWE                        Zimbabwe  2016          42.500000
17         AFE       Eastern & Southern Africa  2017          40.223744
18         AFW        Western & Central Africa  2017          48.900728
19         ARB                      Arab World  2017          90.351067

In [180]:
# Ensure 0 ≤ electricityAccess ≤ 100
invalid_low = df[df['electricityAccess'] < 0]
invalid_high = df[df['electricityAccess'] > 100]

print("Below 0:", len(invalid_low))
print("Above 100:", len(invalid_high))

Below 0: 0
Above 100: 0

In [181]:
df_b42000 =df[df['year'] < 2000]
df_after2000 = df[df['year'] >= 2000]
# count the number of countries before 2000
print("Records :", len(df['countryCode'].unique()))
print("Records before 2000:", len(df_b42000['countryCode'].unique()))
print("Records after 2000:", len(df_after2000['countryCode'].unique()))

Records : 264
Records before 2000: 199
Records after 2000: 263

In [182]:
# Remove records before 2000
df = df[df['year'] >= 2000]

In [183]:
aggregate_codes = {
    'AFE','AFW','ARB','CEB','CSS','EAR','EAS','EAP','EMU','ECA','ECS','EUU',
    'FCS','HIC','IBD','HPC','IDA','IBT','IDB','IDX','LAC','LDC','LMY','LMC',
    'LTE','MEA','MNA','MIC','LCN','NAC','LIC','OED','OSS','PRE','PSS','PST',
    'SSA','TEA','TEC','TSA','TMN','TSS','UMC','SAS','WLD','SSF','SST','TLA'
}

In [184]:
# Countries
df_countries = df[~df['countryCode'].isin(aggregate_codes)]

# Aggregates
df_groups = df[df['countryCode'].isin(aggregate_codes)]

In [185]:
df_countries.head(50)

    countryCode            countryName  year  electricityAccess
16          ZWE               Zimbabwe  2016               42.5
29          ZMB                 Zambia  2017               40.3
30          ZWE               Zimbabwe  2017               44.0
42          VNM                Vietnam  2009               96.1
43          VIR  Virgin Islands (U.S.)  2009              100.0
44          PSE     West Bank and Gaza  2009               99.9
45          YEM            Yemen, Rep.  2009               59.6
46          ZMB                 Zambia  2009               26.6
47          ZWE               Zimbabwe  2009               43.4
55          ZMB                 Zambia  2018               40.2
56          ZWE               Zimbabwe  2018               45.4
68          YEM            Yemen, Rep.  2011               62.0
69          ZMB                 Zambia  2011               28.3
70          ZWE               Zimbabwe  2011               36.9
81          ZMB                 Zambia  2014               27.9
82          ZWE               Zimbabwe  2014               32.3
94          ZWE               Zimbabwe  2012               44.0
107         VUT                Vanuatu  2002               25.7
108         VEN          Venezuela, RB  2002               99.8
109         VNM                Vietnam  2002               89.1
110         VIR  Virgin Islands (U.S.)  2002              100.0
111         PSE     West Bank and Gaza  2002               99.2
112         YEM            Yemen, Rep.  2002               51.5
113         ZMB                 Zambia  2002               17.4
114         ZWE               Zimbabwe  2002               34.2
122         VEN          Venezuela, RB  2010               99.1
123         VNM                Vietnam  2010               97.4
124         VIR  Virgin Islands (U.S.)  2010              100.0
125         PSE     West Bank and Gaza  2010               99.9
126         YEM            Yemen, Rep.  2010               60.8
127         ZMB                 Zambia  2010               22.0
128         ZWE               Zimbabwe  2010               38.9
135         VUT                Vanuatu  2001               24.0
136         VEN          Venezuela, RB  2001               99.9
137         VNM                Vietnam  2001               88.9
138         VIR  Virgin Islands (U.S.)  2001              100.0
139         PSE     West Bank and Gaza  2001               99.1
140         YEM            Yemen, Rep.  2001               50.4
141         ZMB                 Zambia  2001               20.2
142         ZWE               Zimbabwe  2001               34.2
150         PSE     West Bank and Gaza  2020              100.0
151         YEM            Yemen, Rep.  2020               73.9
152         ZMB                 Zambia  2020               44.6
153         ZWE               Zimbabwe  2020               52.7
165         UZB             Uzbekistan  2003               99.5
166         VUT                Vanuatu  2003               27.5
167         VEN          Venezuela, RB  2003               95.7
168         VNM                Vietnam  2003               90.3
169         VIR  Virgin Islands (U.S.)  2003              100.0
170         PSE     West Bank and Gaza  2003               99.1

In [186]:
df_groups.head(10)

   countryCode                     countryName  year  electricityAccess
9          AFE       Eastern & Southern Africa  2000          19.917256
10         AFW        Western & Central Africa  2000          34.246116
11         ARB                      Arab World  2000          80.458667
12         CSS          Caribbean small states  2000          88.415929
13         CEB  Central Europe and the Baltics  2000          97.926264
14         EAR      Early-demographic dividend  2000          67.500489
15         EAS             East Asia & Pacific  2000          92.061814
17         AFE       Eastern & Southern Africa  2017          40.223744
18         AFW        Western & Central Africa  2017          48.900728
19         ARB                      Arab World  2017          90.351067

In [187]:
region_df = pd.read_csv("data/country_region.csv")

In [188]:
# Merge region information with the countries dataset
df_countries = df_countries.merge(region_df, on='countryCode', how='left')

In [189]:
df_countries.info()

<class 'pandas.DataFrame'>
RangeIndex: 5135 entries, 0 to 5134
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   countryCode        5135 non-null   str
 1   countryName        5135 non-null   str
 2   year               5135 non-null   int64
 3   electricityAccess  5135 non-null   float64
 4   region             1176 non-null   str
dtypes: float64(1), int64(1), str(3)
memory usage: 200.7 KB

In [190]:
missing = df_countries[df_countries['region'].isna()]
print(missing['countryCode'].unique())

<StringArray>
['PSE', 'YEM', 'VUT', 'VEN', 'UZB', 'AFG', 'ALB', 'DZA', 'AND', 'AGO',
 ...
 'FSM', 'MLT', 'MHL', 'MRT', 'MUS', 'LCA', 'MAF', 'VCT', 'SDN', 'SUR']
Length: 166, dtype: str

In [191]:
missing.head(20)

   countryCode         countryName  year  electricityAccess region
5          PSE  West Bank and Gaza  2009               99.9    NaN
6          YEM         Yemen, Rep.  2009               59.6    NaN
11         YEM         Yemen, Rep.  2011               62.0    NaN
17         VUT             Vanuatu  2002               25.7    NaN
18         VEN       Venezuela, RB  2002               99.8    NaN
21         PSE  West Bank and Gaza  2002               99.2    NaN
22         YEM         Yemen, Rep.  2002               51.5    NaN
25         VEN       Venezuela, RB  2010               99.1    NaN
28         PSE  West Bank and Gaza  2010               99.9    NaN
29         YEM         Yemen, Rep.  2010               60.8    NaN
32         VUT             Vanuatu  2001               24.0    NaN
33         VEN       Venezuela, RB  2001               99.9    NaN
36         PSE  West Bank and Gaza  2001               99.1    NaN
37         YEM         Yemen, Rep.  2001               50.4    NaN
40         PSE  West Bank and Gaza  2020              100.0    NaN
41         YEM         Yemen, Rep.  2020               73.9    NaN
44         UZB          Uzbekistan  2003               99.5    NaN
45         VUT             Vanuatu  2003               27.5    NaN
46         VEN       Venezuela, RB  2003               95.7    NaN
49         PSE  West Bank and Gaza  2003               99.1    NaN

In [192]:
# Drop records with missing region information
df_countries = df_countries.dropna(subset=['region'])
df_countries.info()

<class 'pandas.DataFrame'>
Index: 1176 entries, 0 to 5129
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   countryCode        1176 non-null   str
 1   countryName        1176 non-null   str
 2   year               1176 non-null   int64
 3   electricityAccess  1176 non-null   float64
 4   region             1176 non-null   str
dtypes: float64(1), int64(1), str(3)
memory usage: 55.1 KB

In [193]:
# Save the cleaned dataset
df_countries.to_csv("data/cleaned_electricity_access.csv", index=False)